# Generated by Django 4.1.1 on 2022-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SansaNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=400, null=True)),
                ('url', models.FileField(max_length=200, upload_to='Avisos/')),
            ],
            options={
                'db_table': 'Avisos',
            },
        ),
        migrations.DeleteModel(
            name='Carpetas',
        ),
    ]
